### ISSUE TITLE
Push failing with undefined method `headers' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jtippett** [ricardochimal/taps#87]
Hey,

I have been trialling taps with some success however it seems to be somewhat fragile on larger tables, blowing up randomly as so:

`Sending schema
Schema:        100% |========================================================================| Time: 00:00:01
Sending data
1 tables, 14,179,280 records
/home/svc-rails/.rvm/gems/ruby-1.9.2-p290/gems/taps-0.3.23/lib/taps/utils.rb:173:in `reraise_server_exception': undefined method `headers' for nil:NilClass (NoMethodError)
        from /home/svc-rails/.rvm/gems/ruby-1.9.2-p290/gems/taps-0.3.23/lib/taps/operation.rb:522:in `rescue in block (2 levels) in push_data_from_table'
        from /home/svc-rails/.rvm/gems/ruby-1.9.2-p290/gems/taps-0.3.23/lib/taps/operation.rb:507:in `block (2 levels) in push_data_from_table'`

In this case, it was not even 10% through those 14m records. It is working fine, then the progress bar suddenly jumps to 100% and it crashes.

Has anyone else seen this? Known issue? BTW I tried running on webrick and then on Thin; same results.

**Comment by ricardochimal** [comment]
try it in ruby 1.8.7, I'm not 100% sure it works with 1.9.2 in all cases yet

**Comment by jtippett** [comment]
Thanks, that seems to have fixed the problem!

**Comment by jtippett** [comment]
hm. Actually, it's not fixed. Seems very random.
`Sending schema
Schema:        100% |========================================================================| Time: 00:00:00
Sending data
1 tables, 165,456 records
/home/svc-rails/.rvm/gems/ruby-1.8.7-p352/gems/taps-0.3.23/bin/../lib/taps/utils.rb:173:in `reraise_server_exception': undefined method `headers' for nil:NilClass (NoMethodError)
        from /home/svc-rails/.rvm/gems/ruby-1.8.7-p352/gems/taps-0.3.23/bin/../lib/taps/operation.rb:522:in `push_data_from_table'
        from /home/svc-rails/.rvm/gems/ruby-1.8.7-p352/gems/taps-0.3.23/bin/../lib/taps/utils.rb:102:in `calculate_chunksize'
        from /home/svc-rails/.rvm/gems/ruby-1.8.7-p352/gems/taps-0.3.23/bin/../lib/taps/operation.rb:491:in `push_data_from_table'
        from /home/svc-rails/.rvm/gems/ruby-1.8.7-p352/gems/taps-0.3.23/bin/../lib/taps/operation.rb:481:in `loop'`

**Comment by ZsoltMaslanyi** [comment]
I have exactly the same problem. Tried it on Ruby 1.8.7 and 1.9.2. No luck.

**Comment by ricardochimal** [comment]
if you guys are on heroku i would open a support ticket with them, if not can you give me info on what gems you have installed, what OS, and if possible a sample sql dump that has the same behavior.

**Comment by f3r** [comment]
I had the same issue because I manually deleted a migration:

```
bd/migrate/XXX_mymigration.rb 
and it's content in schema.rb
```

but somehow forgot to remove the XXX from the 'schema_migrations' table.

If that is your case, try to run:

```
mysql -u user -p -e 'DELETE from YOURDB.schema_migrations WHERE version='XXX'' YOURDB
git commit -a
git push heroku master
heroku db:push --confirm YOURAPPNAME
```

And it works ;)

**Comment by soulnafein** [comment]
Any easy way to find out if that is the problem? I periodically delete migration from the db/migrate folder.
I get the same problem but I don't know how to solve it.

**Comment by nguyenchiencong** [comment]
It's a pain in the ass ;)

**Comment by nixa** [comment]
I also have this problem :/

**Comment by mliu7** [comment]
Had the same issue and am using Django, not Rails. So I think it doesn't have anything to do with the db/migrate folder. Quoting someone from StackOverflow: "Heroku support recomended me not to use taps for large databases because it fails with no reason. "

My db is only about 9 MB in size and the db:push failed about half way through. I then re-ran the exact same command and it finished the push with no problems.

**Comment by mliu7** [comment]
Also, I'm using Ruby 1.8.7 so that's definitely not the fix here.

**Comment by bryanmao** [comment]
I resolved this by using pgbackups to blow away my heroku db with my local db (local was more current, guessing this could work the other way too).  After this, it seems as though heroku db:push is working again.

http://devcenter.heroku.com/articles/pgbackups

**Comment by lawwantsin** [comment]
The fix I found works every time is to delete your db/schema.rb file and run rake db:schema:dump to make a new one.  then push.

I think taps is using the schema.rb file to recreate the tables remotely.  If you change your database column names or anything else at the database level during development, instead of using migrations (like ur sposta) it doesn't know the new changes and can't act accordingly.  

Anyway, updating your schema.rb to actually reflect the local data structure that you're pushing is the truth and the way.
